
- name: 'create artifactory database'
  postgresql_db: name=artifactory template='template0' encoding='UTF-8'

- name: 'create artifactory database user'
  postgresql_user: db=artifactory name='{{artifactory_username}}' password='{{artifactory_password}}'

- name: 'download jdbc connector for postgres'
  get_url: url={{postgres_jdbc_url}} dest={{artifactory_home}}/tomcat/lib
  register: jdbc_installed

- name: 'enable postgresql driver'
  template: src=storage_postgresql.j2 dest={{artifactory_home}}/etc/storage.properties owner=root group=root mode=0644

